# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "ahci"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.luks.devices."luks-e6aab168-d0c0-4d91-94ea-ee92c2a0922f".device =
    "/dev/disk/by-uuid/e6aab168-d0c0-4d91-94ea-ee92c2a0922f";
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/luks-4e35d94a-40bd-4068-81c4-d0098d01b885";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-4e35d94a-40bd-4068-81c4-d0098d01b885".device =
    "/dev/disk/by-uuid/4e35d94a-40bd-4068-81c4-d0098d01b885";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/98E2-5278";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/mapper/luks-e6aab168-d0c0-4d91-94ea-ee92c2a0922f"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
